# Generated by Django 4.1.3 on 2022-11-06 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dosen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_dosen", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Data_alumni",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tanggal_input", models.DateField()),
                ("nama_lengkap", models.CharField(max_length=100)),
                ("nama_panggilan", models.CharField(max_length=50)),
                ("npm", models.CharField(max_length=10)),
                ("tahun_masuk", models.IntegerField()),
                ("tahun_lulus", models.IntegerField()),
                ("tema_skripsi", models.CharField(max_length=200)),
                ("kota_asal", models.CharField(max_length=200)),
                ("kota_sekarang", models.CharField(max_length=200)),
                ("nomor_kontak", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=100)),
                ("media_sosial", models.CharField(max_length=200)),
                ("jabatan_sekarang", models.CharField(max_length=100)),
                ("nama_instansi", models.CharField(max_length=200)),
                ("masa_kerja", models.IntegerField()),
                ("gelar_pascasarjana", models.CharField(max_length=20)),
                ("kampus_pascasarjana", models.CharField(max_length=100)),
                ("lulus_pascasarjana", models.IntegerField()),
                ("catatan", models.TextField()),
                (
                    "dosen_wali",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="database.dosen"
                    ),
                ),
            ],
        ),
    ]
