# Generated by Django 4.1.3 on 2022-11-11 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0002_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="data_alumni",
            name="tanggal_input",
        ),
        migrations.AddField(
            model_name="data_alumni",
            name="resume",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="data_alumni",
            name="tema_tesis",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="data_alumni",
            name="username",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="database.user",
            ),
        ),
        migrations.AlterField(
            model_name="data_alumni",
            name="catatan",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="data_alumni",
            name="kampus_pascasarjana",
            field=models.CharField(max_length=200),
        ),
    ]
