# Generated by Django 4.1.3 on 2022-11-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0004_remove_data_alumni_username_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeeksModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("last_modified", models.DateTimeField(auto_now_add=True)),
                ("img", models.ImageField(upload_to="images/")),
            ],
        ),
    ]
